-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.addresses
(
    id bigserial NOT NULL,
    customer_id bigint,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_default boolean DEFAULT false,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    company character varying(100) COLLATE pg_catalog."default",
    address_line1 character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address_line2 character varying(255) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    postal_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    country character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT addresses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.admin_logs
(
    id serial NOT NULL,
    user_id integer,
    action character varying(100) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(50) COLLATE pg_catalog."default",
    entity_id integer,
    old_values jsonb,
    new_values jsonb,
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.blog_posts
(
    id bigserial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    excerpt text COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    featured_image character varying(255) COLLATE pg_catalog."default",
    author character varying(255) COLLATE pg_catalog."default" NOT NULL,
    author_avatar character varying(255) COLLATE pg_catalog."default",
    reading_time integer,
    category character varying(100) COLLATE pg_catalog."default",
    tags text COLLATE pg_catalog."default",
    view_count integer DEFAULT 0,
    is_published boolean DEFAULT false,
    published_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
    CONSTRAINT blog_posts_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.cart_items
(
    id bigserial NOT NULL,
    session_id character varying(255) COLLATE pg_catalog."default",
    customer_id bigint,
    product_id bigint,
    product_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    product_image character varying(255) COLLATE pg_catalog."default",
    unit_price numeric(10, 2) NOT NULL,
    quantity integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    icon character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    id bigserial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    birth_date date,
    gender character varying(20) COLLATE pg_catalog."default",
    university character varying(255) COLLATE pg_catalog."default",
    study_field character varying(100) COLLATE pg_catalog."default",
    graduation_year integer,
    skin_type character varying(50) COLLATE pg_catalog."default",
    skin_concerns text COLLATE pg_catalog."default",
    is_verified boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    last_login timestamp without time zone,
    address character varying(255) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    postal_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.delivery_options
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price double precision NOT NULL,
    delivery_time_min integer,
    delivery_time_max integer,
    delivery_time_unit character varying(20) COLLATE pg_catalog."default" DEFAULT 'jours'::character varying,
    is_active boolean DEFAULT true,
    is_default boolean DEFAULT false,
    is_express boolean DEFAULT false,
    tracking_available character varying(255) COLLATE pg_catalog."default",
    restrictions text COLLATE pg_catalog."default",
    sort_order integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT delivery_options_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.faqs
(
    id bigserial NOT NULL,
    question text COLLATE pg_catalog."default" NOT NULL,
    answer text COLLATE pg_catalog."default" NOT NULL,
    category character varying(100) COLLATE pg_catalog."default" NOT NULL,
    subcategory character varying(100) COLLATE pg_catalog."default",
    helpful_count integer DEFAULT 0,
    view_count integer DEFAULT 0,
    is_active boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT faqs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.loyalty_programs
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    points_multiplier double precision NOT NULL,
    discount_percentage double precision NOT NULL,
    min_points integer,
    max_points integer,
    is_active boolean DEFAULT true,
    benefits text COLLATE pg_catalog."default",
    next_reward text COLLATE pg_catalog."default",
    sort_order integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT loyalty_programs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.loyalty_rewards
(
    id bigserial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    points_required integer NOT NULL,
    category character varying(100) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    is_popular boolean DEFAULT false,
    sort_order integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT loyalty_rewards_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.newsletter_subscribers
(
    id bigserial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    last_name character varying(100) COLLATE pg_catalog."default",
    university character varying(255) COLLATE pg_catalog."default",
    study_field character varying(100) COLLATE pg_catalog."default",
    graduation_year integer,
    skin_type character varying(50) COLLATE pg_catalog."default",
    source character varying(50) COLLATE pg_catalog."default" DEFAULT 'homepage'::character varying,
    student_verified boolean DEFAULT false,
    promo_code_used character varying(50) COLLATE pg_catalog."default",
    guide_downloaded boolean DEFAULT false,
    weekly_tips_active boolean DEFAULT true,
    subscription_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_email_sent timestamp without time zone,
    email_count integer DEFAULT 0,
    unsubscribe_reason text COLLATE pg_catalog."default",
    unsubscribe_date timestamp without time zone,
    CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id),
    CONSTRAINT newsletter_subscribers_email_key UNIQUE (email)
);

COMMENT ON TABLE public.newsletter_subscribers
    IS 'Table pour la communauté PureSkin - étudiants inscrits à la newsletter';

COMMENT ON COLUMN public.newsletter_subscribers.source
    IS 'Source d''inscription: homepage, product_page, checkout, etc.';

COMMENT ON COLUMN public.newsletter_subscribers.student_verified
    IS 'Si l''email étudiant a été vérifié';

COMMENT ON COLUMN public.newsletter_subscribers.promo_code_used
    IS 'Code promo utilisé par l''étudiant';

COMMENT ON COLUMN public.newsletter_subscribers.guide_downloaded
    IS 'Si le guide PDF a été téléchargé';

COMMENT ON COLUMN public.newsletter_subscribers.weekly_tips_active
    IS 'Si l''étudiant reçoit encore les conseils hebdomadaires';

CREATE TABLE IF NOT EXISTS public.order_items
(
    id bigserial NOT NULL,
    order_id bigint,
    product_id bigint,
    product_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    product_image character varying(255) COLLATE pg_catalog."default",
    unit_price numeric(10, 2) NOT NULL,
    quantity integer NOT NULL,
    total_price numeric(10, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigserial NOT NULL,
    order_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    customer_id bigint,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    payment_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    payment_method character varying(50) COLLATE pg_catalog."default",
    subtotal numeric(10, 2) NOT NULL,
    shipping_cost numeric(10, 2) DEFAULT 0,
    tax_amount numeric(10, 2) DEFAULT 0,
    total_amount numeric(10, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" DEFAULT 'EUR'::character varying,
    shipping_address text COLLATE pg_catalog."default",
    billing_address text COLLATE pg_catalog."default",
    tracking_number character varying(100) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    shipped_at timestamp without time zone,
    delivered_at timestamp without time zone,
    wallet_id character varying(255) COLLATE pg_catalog."default",
    session_token character varying(500) COLLATE pg_catalog."default",
    faroty_user_id character varying(255) COLLATE pg_catalog."default",
    paid_at timestamp(6) without time zone,
    customer_email character varying(255) COLLATE pg_catalog."default",
    customer_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_order_number_key UNIQUE (order_number)
);

COMMENT ON COLUMN public.orders.wallet_id
    IS 'ID du wallet Faroty associé à la commande';

COMMENT ON COLUMN public.orders.session_token
    IS 'Token de session de paiement Faroty';

COMMENT ON COLUMN public.orders.faroty_user_id
    IS 'ID utilisateur Faroty';

CREATE TABLE IF NOT EXISTS public.payments
(
    id bigserial NOT NULL,
    order_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    customer_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_phone character varying(50) COLLATE pg_catalog."default",
    amount numeric(10, 2) NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" DEFAULT 'XAF'::character varying,
    payment_method character varying(100) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    payment_reference character varying(255) COLLATE pg_catalog."default",
    faroty_transaction_id character varying(255) COLLATE pg_catalog."default",
    faroty_wallet_id character varying(255) COLLATE pg_catalog."default",
    products text COLLATE pg_catalog."default",
    shipping_address text COLLATE pg_catalog."default",
    billing_address text COLLATE pg_catalog."default",
    metadata text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    processed_at timestamp without time zone,
    expires_at timestamp without time zone,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT payments_order_id_key UNIQUE (order_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id bigserial NOT NULL,
    category_id bigint,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(10, 2) NOT NULL,
    original_price numeric(10, 2),
    image character varying(255) COLLATE pg_catalog."default",
    badge character varying(50) COLLATE pg_catalog."default",
    stock_quantity integer DEFAULT 0,
    is_active boolean DEFAULT true,
    is_featured boolean DEFAULT false,
    rating_average numeric(3, 2) DEFAULT 0,
    review_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    category character varying(255) COLLATE pg_catalog."default",
    is_promotional boolean,
    image_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.products_categories
(
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT products_categories_pkey PRIMARY KEY (product_id, category_id)
);

CREATE TABLE IF NOT EXISTS public.promotions
(
    id bigserial NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    discount_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    discount_value numeric(10, 2) NOT NULL,
    minimum_amount numeric(10, 2),
    usage_limit integer,
    usage_count integer DEFAULT 0,
    starts_at timestamp without time zone,
    ends_at timestamp without time zone,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT promotions_pkey PRIMARY KEY (id),
    CONSTRAINT promotions_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.routines
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    image character varying(255) COLLATE pg_catalog."default",
    skin_type character varying(50) COLLATE pg_catalog."default",
    skin_concerns text COLLATE pg_catalog."default",
    steps text COLLATE pg_catalog."default",
    duration_minutes integer,
    difficulty_level character varying(50) COLLATE pg_catalog."default",
    products_needed text COLLATE pg_catalog."default",
    is_recommended boolean DEFAULT false,
    view_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT routines_pkey PRIMARY KEY (id),
    CONSTRAINT routines_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.testimonials
(
    id bigserial NOT NULL,
    customer_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_email character varying(255) COLLATE pg_catalog."default",
    customer_avatar character varying(255) COLLATE pg_catalog."default",
    customer_university character varying(255) COLLATE pg_catalog."default",
    customer_age integer,
    customer_city character varying(100) COLLATE pg_catalog."default",
    comment text COLLATE pg_catalog."default" NOT NULL,
    rating integer NOT NULL,
    product_name character varying(255) COLLATE pg_catalog."default",
    product_id bigint,
    is_verified_purchase boolean DEFAULT false,
    is_approved boolean DEFAULT false,
    helpful_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT testimonials_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transactions
(
    id bigserial NOT NULL,
    amount double precision NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    failure_reason character varying(255) COLLATE pg_catalog."default",
    faroty_response text COLLATE pg_catalog."default",
    order_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    payment_method character varying(255) COLLATE pg_catalog."default" NOT NULL,
    processed_at timestamp(6) without time zone,
    session_token character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    transaction_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    wallet_id character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT transactions_pkey PRIMARY KEY (id),
    CONSTRAINT uk_6plyfbm3wy6ds7hongoml5xbk UNIQUE (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.user_sessions
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    session_token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT user_sessions_session_token_key UNIQUE (session_token)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'user'::character varying,
    is_active boolean DEFAULT true,
    last_login timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    country_code character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    profile_picture_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.wishlist_items
(
    id bigserial NOT NULL,
    customer_id bigint,
    product_id bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wishlist_items_pkey PRIMARY KEY (id),
    CONSTRAINT wishlist_items_customer_id_product_id_key UNIQUE (customer_id, product_id)
);

ALTER TABLE IF EXISTS public.addresses
    ADD CONSTRAINT addresses_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.admin_logs
    ADD CONSTRAINT admin_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_admin_logs_user_id
    ON public.admin_logs(user_id);


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_cart_customer
    ON public.cart_items(customer_id);


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_orders_customer
    ON public.orders(customer_id);


ALTER TABLE IF EXISTS public.products_categories
    ADD CONSTRAINT products_categories_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_products_categories_category
    ON public.products_categories(category_id);


ALTER TABLE IF EXISTS public.products_categories
    ADD CONSTRAINT products_categories_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_products_categories_product
    ON public.products_categories(product_id);


ALTER TABLE IF EXISTS public.testimonials
    ADD CONSTRAINT testimonials_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_sessions
    ADD CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_user_id
    ON public.user_sessions(user_id);


ALTER TABLE IF EXISTS public.wishlist_items
    ADD CONSTRAINT wishlist_items_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.wishlist_items
    ADD CONSTRAINT wishlist_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;